### ISSUE TITLE
No cargan algunos emojis en Android

### ISSUE THREAD

**Issue by lgaticaq** [raulghm/react-asado#3]
Testeado en Android 5.0.2 y Brave 1.0.42 (Chromium 64.0.3282.137)
![screenshot_2018-03-26-08-07-20](https://user-images.githubusercontent.com/661958/37903101-07e71008-30f7-11e8-90b7-84338b3e1860.png)

**Comment by raulghm** [comment]
Solucionado en la ultima version, gracias por reportar, sl2!
