### ISSUE TITLE
embutidos y el pan

### ISSUE THREAD

**Issue by juanbrujo** [raulghm/react-asado#4]
![alguien-por-favor-quiere-incluir-embutidos-y-el-pan](https://user-images.githubusercontent.com/362186/38066012-5b8913a0-32dc-11e8-97f7-f4a1a42ef9b6.jpg)

**Comment by raulghm** [comment]
trabajando en ellos @juanbrujo

**Comment by raulghm** [comment]
Agregados @juanbrujo ;)
